CBV_Project/CBV_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^mygeneric/',include('GenericViews.urls'))
]

CBV_Project/GenericViews/urls.py
from GenericViews import views
from django.conf.urls import url

app_name = 'GenericViews'

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailsViews.as_view(),name='detail'),

    url(r'makeentry/$',views.makeentry , name='makeentry'),
]

CBV_Project/GenericViews/models.py
from django.db import models

class Person(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)

    def __str__(self):
        return self.name

CBV_Project/GenericViews/forms.py
from django import forms

class PersonForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : 'Enter Name'
            }
        )
    )

    desc = forms.CharField(
        help_text="write a brief about a person.",

        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter Description'
            }
        )
    )

CBV_Project/GenericViews/views.py
from django.shortcuts import render

from  django.views import generic
from GenericViews.forms import PersonForm
from .models import Person

def makeentry(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            desc = request.POST.get('desc')

        person = Person(name=name, desc=desc)
        person.save()

        form = PersonForm()
        return render(request,'makeentry.html',{'form':form})

    else :
        form = PersonForm()
        return render(request,'makeentry.html',{'form':form})


class IndexView(generic.ListView):
    context_object_name = 'list'
    template_name = 'index.html'

    def get_queryset(self):
        return Person.objects.all()



class DetailsViews(generic.DetailView):
    queryset = Person.objects.all()
    context_object_name = 'list'
    template_name = 'detail.html'

    def get_queryset(self, queryset=queryset):
        return queryset

CBV_Project/templates/detail.html
{% if list %}
    <h1>About {{ list.name }} is:</h1>
    <h3>Id is :{{ list.id }} </h3>
    <h3>Name is :{{ list.name }} </h3>
    <h3>His description is :{{ list.desc }} </h3>

    <hr>

    <table>
       <tr>
           <th>Id :</th>
           <td>{{ list.id }}</td>
       </tr>
        <tr>
            <th>Name :</th>
           <td>{{ list.name }}</td>
        </tr>
        <tr>
           <th>Details :</th>
           <td>{{ list.desc }}</td>
       </tr>
    </table>
{% else %}
    <h1>No data</h1>

{% endif %}

CBV_Project/templates/index.html
{% if list %}
<h1>Person Details</h1>
<ul>
    {% for person in list %}
    <li>
        <a href="{% url 'GenericViews:detail' person.id %}">{{ person.name }}</a>

    </li>
    {% endfor %}
</ul>

{% else %}
    <h1>Sorry No data.</h1>

{% endif %}

CBV_Project/templates/makeentry.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>


<body>
<div class="container">
    <h1 class="text-center">Please make entries here.</h1>
    <div class="row">
        <div class="col-md-5">
            <form  method="POST">
{#            <form action="{% url 'makeentry' %}" method="POST">#}
                {% csrf_token %}
                {{ form }}<br>
                <center>
                    <input type="submit" value="Submit">
                </center>
            </form>
        </div>
    </div>
</div>
</body>